### ISSUE TITLE
arm64 报错了

### ISSUE THREAD

**Issue by zhonghaibin** [llychao/m3u8-downloader#32]
$ ./m3u8-downloader  -u=http://devimages.apple.com/iphone/samples/bipbop/bipbopall.m3u8 -ht=apiv2
[功能]:多线程下载直播流 m3u8 视屏（ts + 合并）
[提醒]:如果下载失败，请使用 -ht=apiv2 
[提醒]:如果下载失败，m3u8 地址可能存在嵌套
[提醒]:如果进度条中途下载失败，可重复执行
待下载 ts 文件数量: 4
[Downloading] ■■■■■■■■■■■■■■■■■■■■ 100.00% 	00002.tspanic: exit status 1

goroutine 1 [running]:
main.execUnixShell({0x2994f3, 0x15})
	/home/pi/go/m3u8-downloader-master/m3u8-downloader.go:331 +0x1c4
main.unix_merge_file({0x400012c180, 0x28})
	/home/pi/go/m3u8-downloader-master/m3u8-downloader.go:361 +0x48
main.Run()
	/home/pi/go/m3u8-downloader-master/m3u8-downloader.go:131 +0x64c
main.main()
	/home/pi/go/m3u8-downloader-master/m3u8-downloader.go:71 +0x20

**Comment by llychao** [comment]
> $ ./m3u8-downloader -u=http://devimages.apple.com/iphone/samples/bipbop/bipbopall.m3u8 -ht=apiv2 [功能]:多线程下载直播流 m3u8 视屏（ts + 合并） [提醒]:如果下载失败，请使用 -ht=apiv2 [提醒]:如果下载失败，m3u8 地址可能存在嵌套 [提醒]:如果进度条中途下载失败，可重复执行 待下载 ts 文件数量: 4 [Downloading] ■■■■■■■■■■■■■■■■■■■■ 100.00% 00002.tspanic: exit status 1
> 
> goroutine 1 [running]: main.execUnixShell({0x2994f3, 0x15}) /home/pi/go/m3u8-downloader-master/m3u8-downloader.go:331 +0x1c4 main.unix_merge_file({0x400012c180, 0x28}) /home/pi/go/m3u8-downloader-master/m3u8-downloader.go:361 +0x48 main.Run() /home/pi/go/m3u8-downloader-master/m3u8-downloader.go:131 +0x64c main.main() /home/pi/go/m3u8-downloader-master/m3u8-downloader.go:71 +0x20

访问受限了。

**Comment by hangcheng-wu** [comment]
我这边也是
goroutine 1 [running]:
main.ExecUnixShell(0x2b2d1b, 0x15)
        /sharedfolders/disk1root/media/m3u8-downloader-2.0/m3u8-downloader.go:319 +0x1c8
main.unix_merge_file(0x4000156140, 0x38)
        /sharedfolders/disk1root/media/m3u8-downloader-2.0/m3u8-downloader.go:349 +0x48
main.Run()
        /sharedfolders/disk1root/media/m3u8-downloader-2.0/m3u8-downloader.go:125 +0x4c0
main.main()
        /sharedfolders/disk1root/media/m3u8-downloader-2.0/m3u8-downloader.go:69 +0x20

**Comment by Seeger0216** [comment]
请问如何解决？
